#version: "3.3"

services:
  unit4:
    container_name: unit4
    build:
      context: "./4_Policy_Gradient"
      dockerfile: Dockerfile
    env_file:
      - .env
    tty: true
    volumes:
      - "./4_Policy_Gradient:/HOME"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  unit5_snowball:
    container_name: unit5_snowball
    build:
      context: "./5_Unity_ML_Agents/Snowball"
      dockerfile: Dockerfile
    env_file:
      - .env
    tty: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  unit5_pyramids:
    container_name: unit5_pyramids
    build:
      context: "./5_Unity_ML_Agents/Pyramids"
      dockerfile: Dockerfile
    env_file:
      - .env
    tty: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
